name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*"  ]

env:
  CARGO_TERM_COLOR: always

jobs:
   build_matrix: 
     name: Run tests for ${{ matrix.os }}
     runs-on: ${{ matrix.os }} 
     strategy: 
       matrix: 
         name: [linux, windows, macos]
         include:
            - name: linux 
              os: ubuntu-latest
            - name: windows 
              os: windows-latest 
            - name: macos 
              os: macos-latest

     steps: 
     - uses: actions/checkout@v1
     - uses: actions-rs/toolchain@v1 
       with: 
         profile: minimal 
         toolchain: nightly 
         override: true 
     - name: Install Miri
       run: |
         rustup toolchain install nightly --component miri
         rustup override set nightly
         cargo miri test
     - name: Build
       run: cargo build
     - name: Test 
       run: cargo test
     - name: Miri Test
       run: cargo miri Test
